local a = require('tests.lib.assertions')
return function()
    local modes = require('compat.modes')
    local mode = modes.M({description='Melee Mode'})
    mode:options('TP', 'ACC', 'DT')
    a.equal(mode.value, 'TP')
    a.equal(tostring(mode), 'TP')
    a.equal(mode:cycle(), 'ACC'); a.equal(mode:cycle(), 'DT'); a.equal(mode:cycle(), 'TP')
    a.equal(mode:set('DT'), 'DT')
    a.equal(mode:contains('DT'), true)
    a.equal(mode:contains('BAD'), false)
    a.raises(function() mode:set('BAD') end, 'RahvinCompatError:mode_invalid_option:BAD')
    mode:options('One', 'Two'); a.equal(mode.value, 'One')
    local flag = modes.M(false)
    a.equal(flag.value, false); flag:toggle(); a.equal(flag.value, true)
    a.equal(flag:contains(true), true); a.equal(flag:contains(false), false)
    flag:reset(); a.equal(flag.value, false); flag:set(); a.equal(flag.value, true)
    a.raises(function() mode:toggle() end, 'RahvinCompatError:mode_not_boolean')
    a.raises(function() mode:unknown() end, 'attempt to call')
end
